FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y bison flex make

COPY . /repo
WORKDIR /repo
RUN make -j8
RUN make tools

FROM ubuntu:20.04 as package
COPY --from=builder /repo/tools/dump_policy_bpf/dump_policy_bpf /
